# E0023

The body of this try expression never raises any error.

## Erroneous example

```moonbit
fn main {
  try {
    println("Hello, world!")
  } catch {
    _ => println("Error")
  }
}
```

## Suggestion

Remove the `try` expression:

```moonbit
fn main {
  println("Hello, world!")
}
```
